---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```
```{r}
#install.packages("SportsAnalistics")
library(SportsAnalytics)
NBA1415<-fetch_NBAPlayerStatistics("14-15")

```

#各隊最辛苦的球員
##上場時間最多

```{r}
TotalMinutesPlayed<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
NBA1415TotalMinutesPlayed<-merge(NBA1415,TotalMinutesPlayed)
output<-NBA1415TotalMinutesPlayed[order(NBA1415TotalMinutesPlayed$TotalMinutesPlayed,decreasing=T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digit=2)
```

#各隊得分王
##總得分最高

```{r}
Totalpointsmade<-aggregate(TotalPoints~Team,NBA1415,max)
NBA1415Totalpointsmade<-merge(NBA1415,Totalpointsmade)
output<-NBA1415Totalpointsmade[order(NBA1415Totalpointsmade$TotalPoints,decreasing=T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digit=2)
```

#各隊最有效率的球員
##得分效率最高,三分球擁有1.5倍加權

```{r}
NBA1415$PointsE<-round(((NBA1415$FieldGoalsMade-NBA1415$ThreesMade)*2+(NBA1415$ThreesMade)*3)/NBA1415$TotalMinutesPlayed,digits=3)
PointsEMax<-merge(NBA1415,aggregate(PointsE~Team,NBA1415,max))
output<-PointsEMax[order(PointsEMax$PointsE,decreasing=T),c("Team","Name","Position","PointsE","TotalPoints")]
library(knitr)
kable(output, digit=2)
```

#各隊三分球出手最準的球員
##三分球比三分出手數，三分進球數需高於聯盟平均

```{r}
NBA1415$ThreesP<-round(NBA1415$ThreesMade/NBA1415$ThreesAttempted,digits=3)
ThreesPMax<-merge(NBA1415,aggregate(ThreesP~Team,
                                    NBA1415[NBA1415$ThreesMade>mean(NBA1415$ThreesMade),],
                                    max))
output<-ThreesPMax[order(ThreesPMax$ThreesP,decreasing=T),c("Team","Name","Position","ThreesP","ThreesMade")]
library(knitr)
kable(output, digit=2)

```


